apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pythondev
  name: pythondev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythondev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: evilpetclinic
    spec:
      containers:
      - image: harbor-master-test.rbenavente.demo.twistlock.com/library/pythondev:latest
        name: evilpetclinic
        resources: {}
      imagePullSecrets:
      - name: regcred
status: {}
